import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import '@/app/globals.css';
import { fontVariables } from '@/app/fonts';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { dictionaries, siteUrl } from '@/content';
import { localePath, locales, type Locale } from '@/content/types';

const openGraphLocale: Record<Locale, string> = { en: 'en_US', es: 'es_AR' };

export function localeMetadata(locale: Locale): Metadata {
  const { meta } = dictionaries[locale];
  // Generated by `npm run og` from the built hero headline.
  const shareImage = { url: `/og/${locale}.png`, width: 1200, height: 630, alt: meta.title };
  return {
    metadataBase: new URL(siteUrl),
    title: meta.title,
    description: meta.description,
    alternates: {
      canonical: localePath[locale],
      languages: {
        en: localePath.en,
        es: localePath.es,
        'x-default': localePath.en,
      },
    },
    openGraph: {
      type: 'website',
      siteName: 'Gelum Digital',
      url: localePath[locale],
      title: meta.title,
      description: meta.description,
      locale: openGraphLocale[locale],
      alternateLocale: locales.filter((other) => other !== locale).map((other) => openGraphLocale[other]),
      images: [shareImage],
    },
    twitter: {
      card: 'summary_large_image',
      title: meta.title,
      description: meta.description,
      images: [shareImage],
    },
  };
}

/**
 * Marks `.reveal` sections visible once they enter the viewport (see globals.css).
 * Inline and dependency-free so it never waits on the JS bundle; without
 * IntersectionObserver it does nothing and every section is simply shown.
 */
const revealScript = `(function(){if(!('IntersectionObserver' in window))return;var d=document.documentElement;d.classList.add('js');document.addEventListener('DOMContentLoaded',function(){var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target);}});},{rootMargin:'0px 0px -10% 0px'});document.querySelectorAll('.reveal').forEach(function(el){io.observe(el);});});})();`;

type Props = {
  locale: Locale;
  children: ReactNode;
};

/** The <html> document shared by each language's root layout. */
export default function RootDocument({ locale, children }: Props) {
  const dictionary = dictionaries[locale];

  return (
    // The inline script adds a class to <html> before hydration.
    <html lang={locale} className={fontVariables} suppressHydrationWarning>
      <body>
        {/* First in <body>: runs before any section is parsed or painted. */}
        <script dangerouslySetInnerHTML={{ __html: revealScript }} />
        <a
          href="#main"
          className="sr-only rounded-control bg-ink px-4 py-2 text-sm text-surface focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50"
        >
          {dictionary.skipLink}
        </a>
        <Header locale={locale} dictionary={dictionary} />
        <main id="main" tabIndex={-1} className="focus:outline-none">
          {children}
        </main>
        <Footer locale={locale} dictionary={dictionary} />
      </body>
    </html>
  );
}
